galileo: Fix newlib stub
This patch fixes some issues related to newlib stubs from Galileo
platforms.

The stubs implement the reentrant version of system calls so they
should have been using the errno variable within the struct reent
instead of the global one.

That change has spotted another issue related to the library order in
TARGET_LIBFILES variable. The linker is reporting the following error:

../../platform/galileo/bsp/i586-elf/lib/libm.a(lib_a-w_log.o): In function `log':
w_log.c:(.text+0xd2): undefined reference to `__errno'
w_log.c:(.text+0xfe): undefined reference to `__errno'
w_log.c:(.text+0x22): undefined reference to `__errno'

The issue is that libm needs symbols from libc therefore it should
come ahead in the library order, but it doesn't. For more information
about library order in static linking see [1].

[1] http://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking