[galileo] Fix undefined reference to __umoddi3 and __udivdi3 when calling printf()
After adding '--enable-newlib-io-long-long' to our newlib's configure parameters,
printf ended up reaching a 64bit modulo and a 64bit division at
newlib/libc/stdio/vfprintf.c:1599 and newlib/libc/stdio/vfprintf.c:1620, respectively.

Since these are 64bit operations not provided by 32bit hardware, the underlying
functions are currently being provided by the runtime lib. Thus, we need to link
with libgcc.a to have those symbols.

This commit also adds a printf() call to our platform main() so we can easily spot
future errors like this one.

Please refer to https://gcc.gnu.org/ml/gcc/2002-08/msg01124.html .